POST http://localhost:8080/notes
Content-Type: application/json

{
  "type": "PUBLIC",
  "password": "pass",
  "title": "Test note!",
  "expirationDate": "2030-01-01",
  "data": "This is the public note!"
}